---

sudo: True
language: 'python'
python: '2.7'
services:
  - docker

virtualenv:
    system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq sshpass
  - ssh-keygen -b 2048 -t rsa -f $HOME/.ssh/id_rsa -q -N ""
  - sudo ln -s $PWD/test/ansible /etc/ansible
  - pip install ansible
  - ansible --version

  - docker info
  - docker version
  - docker build -f test/dockerfile/debian8 -t debian8 .
  - docker build -f test/dockerfile/centos7 -t centos7 .
  - docker build -f test/dockerfile/ubuntu14.04 -t ubuntu14.04 .
  - docker run -d --cap-add=SYS_ADMIN -it -v /sys/fs/cgroup:/sys/fs/cgroup:ro debian8
  - docker run -d --cap-add=SYS_ADMIN -it -v /sys/fs/cgroup:/sys/fs/cgroup:ro centos7
  - docker run -d -it ubuntu14.04
  - sleep 10
  - docker inspect --format '{{.Config.Image}} ansible_ssh_host={{.NetworkSettings.IPAddress}}' `docker ps -q` >> /etc/ansible/hosts

script:
  - test/playbooks
  - ansible-playbook /etc/ansible/test.yml --diff


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
