---

sudo: True
language: 'python'
python: '2.7'
services:
  - docker

virtualenv:
    system_site_packages: true

before_install:
  - env
  - docker info
  - docker version

  - git clone --depth 1 https://github.com/le9i0nx/ansible-role-test
  - git clone --depth 1 https://github.com/le9i0nx/ansible-role-data test
  - python ansible-role-test/bin/virt.py

  - pip install git+https://github.com/ansible/ansible.git@v2.0.0-0.6.rc1
  - ansible --version

  - ansible all -m setup -u root
  - ansible-playbook /etc/ansible/test.yml --diff

script:
  - sleep 1

notifications:
  email:
    on_failure: change


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
