---

sudo: True
language: 'python'
python: '2.7'
services:
  - docker

virtualenv:
    system_site_packages: true

env:
  - ANSIBLE_VER=v2.2.2.0-1

before_install:
  - env
  - docker info
  - docker version

  - pip install git+https://github.com/ansible/ansible.git@$ANSIBLE_VER
  - ansible --version

  - git clone --recursive --depth 1 https://github.com/le9i0nx/ansible-role-test test
  - python test/bin/virt.py

  - cd /etc/ansible/ && ansible all -m setup -u root
  - cd /etc/ansible/ && ansible-playbook --diff -v /etc/ansible/test.yml

script:
  - sleep 1

notifications:
  email:
    on_failure: change

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
