---

sudo: true
services:
  - docker

env:
  - distributiv=ubuntu14.04
  - distributiv=debian8
  - distributiv=centos7

before_install:
  - docker info
  - docker version
  - docker build -f test/Dockerfile-${distributiv} -t test-${distributiv} .

script:
  - docker run -i test-${distributiv}

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
