---

- name: install
  include: install.yml
  when: role_syncthing_register_install is not defined

- name: install register
  set_fact:
    role_syncthing_register_install: ""
  when: role_syncthing_register_install is not defined

- name: start
  include: start.yml

- wait_for: port=8384 delay=3 timeout=5

- name: config
  include: config.yml
  when: ((role_syncthing_data is defined) and
         (role_syncthing_data.folders is defined))

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
