---

- name: install
  include: install.yml
  when: role_syncthing_register_install is not defined

- name: install register
  set_fact:
    role_syncthing_register_install: ""
  when: role_syncthing_register_install is not defined

- name: start
  include: start.yml

- name: config
  include: config.yml
  when: ((role_syncthing is defined ) and
         (role_syncthing.inventory_hosts is defined ) and
         (role_syncthing.folders.path is defined ) and
         (role_syncthing.folders.id is defined ))

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
