---

- apt_key:
    data: "{{ lookup('file', 'apt.gpg') }}"
    state: present

- name: add repo
  apt_repository:
    repo: 'deb http://apt.syncthing.net/ syncthing release'
    state: 'present'

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'syncthing'
    - 'python-httplib2' # ansible url

- name: variable redefinition
  set_fact:
    syncthing_path: "/usr/bin"

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
