---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'syncthing'
    - 'syncthing-inotify'
    - 'python-httplib2' # ansible url

- name: variable redefinition
  set_fact:
    syncthing_path: "/usr/bin"

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
