---

- name: install required packages
  yum:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - 'wget'
    - 'python-httplib2' # ansible url

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
