---

- name: install the systemd unit file
  template:
    src: 'etc/systemd/system/syncthing@.service.j2'
    dest: '/etc/systemd/system/syncthing@.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - reload systemd
  when: ((ansible_service_mgr is defined) and
        (ansible_service_mgr in [ "systemd" ]) and
        (ansible_pkg_mgr != "apt"))

- name: register autostart service systemd
  service:
    name: 'syncthing@{{ role_syncthing_user }}'
    enabled: 'yes'
    state: 'started'
  notify: [ 'Restart syncthing' ]
  when: ((ansible_service_mgr is defined) and
        (ansible_service_mgr in [ "systemd" ]))

- name: install the upstart file
  template:
    src: 'etc/init/syncthing.conf.j2'
    dest: '/etc/init/syncthing.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ((ansible_service_mgr is defined) and
        (ansible_service_mgr in [ "upstart" ]))

- name: start syncthing
  service: name=syncthing state=started
  when: ((ansible_service_mgr is defined) and
        (ansible_service_mgr in [ "upstart" ]))

- meta: flush_handlers

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
