---

- name: sysctl add
  shell: sh -c 'echo 204800 > /proc/sys/fs/inotify/max_user_watches'
  when: ((ansible_virtualization_type is defined ) and
         (ansible_virtualization_type != "docker" ))

- name: restart syncthing
  shell: systemctl restart syncthing@{{ role_syncthing_user }}.service
  notify: reload systemd

- name: reload systemd
  shell: systemctl daemon-reload

- name: restart syncthing init.d
  shell: /etc/init.d/syncthing_{{role_syncthing_user}} restart
