---

- name: restart syncthing
  shell: systemctl restart syncthing@{{ role_syncthing_user }}.service

- name: reload systemd
  shell: systemctl daemon-reload

- name: restart syncthing init.d
  service: name=syncthing_{{role_syncthing_user}} state=started
